spring:
  application:
    name: spring-security-project
  data:
    mongodb:
      uri: "mongodb://admin:password@localhost:27017/admin"
      database: basic-auth

application:
  name: spring-security-project
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

logging:
  level:
    root: INFO